version: 1
flags:
  - -trimpath
  - -tags=netgo
env:
  - CGO_ENABLED=0
goos: linux
goarch: amd64
binary: queuety
main: ./server/main  # o ./manager, dependiendo de dónde esté tu main.go
ldflags:
  - -s -w